site_name: Aaron Huntley
site_url: https://aaron-huntley.github.io/mathematics/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: light green
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
nav:
  - Home: index.md
  - About me:
    - CV: cv/education.md
  - Category Theory: 
    - Introduction: category_theory/Introduction.md
    - Categories: category_theory/Categories.md
    - Functors: category_theory/Functors.md
    - Natural Transformations: category_theory/Natural transformations.md
    - Universal morphisms and adjoint functors: category_theory/Universal morphisms and adjoint functors.md
    - Initial and terminal objects: category_theory/Initial and terminal objects.md
    - Monads: category_theory/Monads.md