site_name: Aaron Huntley
site_url: https://aaron-huntley.github.io/mathematics/
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: cyan
      accent: light green
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections