name: build_notes

on:
  push:
    branches:
      - main
    paths:
      - 'docs/notes_tex/**'
      - 'convert_tex_to_md.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material  # plus anything your converter needs

      - name: Convert .tex to .md
        run: python convert_tex_to_md.py

      - name: Commit converted .md files
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add converted/*.md
          git commit -m "Auto-convert .tex → .md" || echo "No changes to commit"
          git push
